fypWebsite/urls.py
from django.conf.urls import url,include
from django.contrib import admin



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mainapp/', include('mainapp.urls')),
]

mainapp/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

music/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [

	#by default url /
    url(r'^$' , views.index, name='index'),

    #for showing the details #/music/712->id
    url(r'^(?P<album_id>[0-9]+)/$' , views.details, name='details'),

    #for sample form
    url(r'^myform/$' , views.form, name='form'),
]

my_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

mainapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class MyClass(models.Model):
	"""docstring for MyClass"""
	text = models.CharField(max_length=500)

	def __str__(self):
		return self.text
	

music/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

class Album(models.Model):
	artist = models.CharField(max_length = 250)
	album_title = models.CharField(max_length = 500)
	genre = models.CharField(max_length = 100)
	album_logo = models.CharField(max_length = 1000)

	def __str__(self):
		return self.album_title + ' - ' + self.artist


class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	song_title = models.CharField(max_length = 250)
	is_favorite = models.BooleanField(default=False)


	def __str__(self):
		return self.song_title

mainapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import MyClass
import nltk
from nltk.corpus import treebank
from nltk.corpus import alpino as alp
from nltk.tag import UnigramTagger, BigramTagger


# Create your views here.

def index(request):
	if request.method == "POST":
		text =  request.POST.get('input')
		tokens = nltk.word_tokenize(text)
		tagged = nltk.pos_tag(tokens)
		context = { 'input': tagged}

	else:
		context = { 'input': "No Data" }
		
	return render(request,'mainapp/index.html',context)

music/views.py
from django.http import Http404
from django.shortcuts import render
from .models import Album


def index(request):
	all_albums = Album.objects.all()
	context = {'all_albums': all_albums}
	return render(request,'music/index.html',context)


def details(request,album_id):
	try:
		album = Album.objects.get( pk = album_id )
	except Album.DoesNotExist:
		raise Http404("Album doesnt exist")

	return render(request,'music/details.html', {'album': album } )

def form(request):

	if request.method == "POST":
		para = request.POST.get('paragraph')
		length = len(para)
		context = { 'para': para, 'length': length }
	else:
		para1 = "no data"
		length1 = 0
		context = { 'para': para1, 'length': length1 }
		 
	return render(request,'music/form.html', context)		

mainapp/templates/mainapp/index.html
<h1>Hello World! My Form</h1>


<form action="" method="post">
	{% csrf_token %}
	<input type="text" name="input" id="input" 
	placeholder="Enter your Input Here">
	<input type="submit" name="process" value="Process">
</form>

<h1>Tagged Text: </h1>

<p>
	{{ input }}
</p>

music/templates/music/details.html
<img src="{{ album.album_logo }}">
<h1>{{ album.album_title }}</h1>
<h2>{{ album.artist }}</h2>

<ul>
{% for song in album.song_set.all %}
<li>{{ song.song_title }}</li>
{% endfor %}

</ul>

music/templates/music/form.html
<h1> My Form </h1>

<form action="" method="post">
	{% csrf_token %}
	<label for="Enter Paragraph">Paragraph:</label></br>
	<textarea rows="4" cols="50" name="paragraph" placeholder="Enter Paragraph here.." ></textarea><br>
	<input type="submit" class="btn btn-primary" name="submit_button">

</form>

<h1>Recently data Entered: </h1>
<p>


	{{ para }}

</p>
<hr>
<p><strong>Words of Paragraph : </strong><b>{{ length }}</b></p>

music/templates/music/index.html
<h2>List of Albums</h2>
<ul>
	{% for album in all_albums %}
<li><a href="/music/{{ album.id }}/">{{ album.album_title }}</a></li>
	{% endfor %}
</ul>